<h1 id="user-content-handling-errors">Handling Errors</h1><ul><li><a href='#user-content-introduction'>Introduction</a></li><li><a href='#user-content-handling-errors'>Handling Errors</a></li><li><a href='#user-content-custom-errors'>Custom Errors</a></li></ul><p>Coast attempts to make clojure exceptions a little nicer by offering two functions: <code>raise</code> and <code>rescue</code></p><p>In this guide, we learn how clojure exceptions are raised, how to write logic around them and finally creating your own custom exceptions.</p><h2 id="user-content-introduction">Introduction</h2><p>Exceptions are great since they halt the program at a certain stage and make sure everything is correct before proceeding.</p><p>Exceptions, especially in clojure, are usually just treated as insane, indecipherable walls of text that tell devs that <em>something</em> went wrong, go dive in and find it.</p><p>By default, Coast handles all exceptions for you and displays them in a nice format during development. However, you are free to handle exceptions however you want.</p><h2 id="user-content-handling-errors">Handling Errors</h2><p>Errors can be handled by catching all of them or specifying a name</p><h3 id="user-content-gotta-catch-'em-all">Gotta Catch 'Em All</h3><p>Here's how <code>raise</code> works with one argument</p><pre><code class="clojure">&#40;raise {:message &quot;This is an error with a message key&quot;}&#41;
</code></pre><p>That raises a <code>clojure.lang.ExceptionInfo</code> exception with <code>ex-data</code>: <code>{:message &quot;This is an error with a message key&quot;}</code></p><p>You can <code>rescue</code> from this instead of using <code>try</code> and <code>catch</code> like this:</p><pre><code class="clojure">&#40;let &#91;&#91;&#95; error&#93; &#40;rescue
                  &#40;raise {:message &quot;This is an error&quot;}&#41;&#41;&#93;&#41;
</code></pre><p>The error variable in the above example now contains <code>{:message &quot;This is an error&quot;}</code></p><p>So <code>rescue</code> is a macro, which wraps the body in <code>try</code> and <code>catch</code> and catches any <code>ExceptionInfo</code> that comes from <code>raise</code></p><h3 id="user-content-named-errors">Named Errors</h3><p>You can rescue individual errors as well</p><pre><code class="clojure">&#40;rescue
  &#40;raise {:message &quot;Error!&quot; :custom true}&#41;
  &#40;raise {:message &quot;Error!&quot;}&#41;
  :custom&#41;
</code></pre><p>In the above example, the first error will be caught, the second one will not.</p><h2 id="user-content-custom-errors">Custom Errors</h2><p><code>raise</code> can also change the "Error has occurred" message as well like this:</p><pre><code class="clojure">&#40;raise &quot;This is a custom error title&quot; {}&#41;
</code></pre>